### ISSUE TITLE
"Unable to retrieve data"

### ISSUE THREAD

**Issue by parpar8090** [samerton/Nameless-VotingPlugin#14]
![image](https://user-images.githubusercontent.com/51650998/131740100-ab336776-847b-4e02-b3a7-a744c3853ea0.png)
Do you know how to fix it?

Db user/pw/name are correct

**Comment by samerton** [comment]
This happens if one of the following columns doesn't exist in the VotingPlugin database table:

- uuid
- PlayerName
- MonthTotal
- AllTimeTotal
- DailyTotal
- WeeklyTotal

_or_ the database table specified by the `table` option in the file `modules/VotingPlugin/config.php` doesn't exist

If you have a means to check the VotingPlugin database to see what's inside there (eg using a tool like phpMyAdmin), can you ensure these exist in the correct table?
